export enum DonorType {
  INDIVIDUAL = "INDIVIDUAL",
  COMPANY = "COMPANY",
  NGO = "NGO",
  SCHOOL = "SCHOOL",
  FOUNDATION = "FOUNDATION",
  GOVERNMENT = "GOVERNMENT"
}

export enum DonationType {
  USED_LAPTOPS = "USED_LAPTOPS",
  DESKTOPS = "DESKTOPS",
  MINI_PCS = "MINI_PCS",
  ACCESSORIES = "ACCESSORIES",
  CORPORATE_RECYCLING = "CORPORATE_RECYCLING",
  SPONSOR_LEARNER = "SPONSOR_LEARNER",
  SPONSOR_CLASSROOM_BUNDLE = "SPONSOR_CLASSROOM_BUNDLE",
  SPONSOR_FULL_LAB = "SPONSOR_FULL_LAB",
  MONTHLY_DONOR = "MONTHLY_DONOR"
}

export enum DonationStatus {
  NEW = "NEW",
  REVIEWING = "REVIEWING",
  CONTACTED = "CONTACTED",
  COLLECTION_NEEDED = "COLLECTION_NEEDED",
  COLLECTION_ARRANGED = "COLLECTION_ARRANGED",
  PROCESSING = "PROCESSING",
  RECEIVED = "RECEIVED",
  COMPLETED = "COMPLETED",
  CLOSED = "CLOSED"
}

export enum DonationPriority {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH"
}
