export enum DeviceCategory {
  STUDENT_LAPTOPS = "STUDENT_LAPTOPS",
  BUSINESS_LAPTOPS = "BUSINESS_LAPTOPS",
  DESKTOP_PCS = "DESKTOP_PCS",
  MINI_PCS = "MINI_PCS",
  ALL_IN_ONE_PCS = "ALL_IN_ONE_PCS",
  COMPUTER_LAB_BUNDLES = "COMPUTER_LAB_BUNDLES",
  AI_LEARNING_LAB_BUNDLES = "AI_LEARNING_LAB_BUNDLES",
  ACCESSORIES = "ACCESSORIES"
}

export enum DeviceRequestStatus {
  NEW = "NEW",
  REVIEWING = "REVIEWING",
  QUOTED = "QUOTED",
  RESERVED = "RESERVED",
  FULFILLED = "FULFILLED",
  CLOSED = "CLOSED"
}

export enum DeviceRequestPriority {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH"
}
